import { z } from "zod";

export const SalutationTitleSchema = z.enum(["MR", "MRS", "MS", "MISS", "DR"]);
export type SalutationTitle = z.infer<typeof SalutationTitleSchema>;
export const DateStringSchema = z.string();
export type DateString = z.infer<typeof DateStringSchema>;
export const EmailSchema = z.string().email();
export type Email = z.infer<typeof EmailSchema>;
export const StateSchema = z.enum(["TAS", "VIC", "NSW", "QLD", "WA", "SA", "ACT", "NT", "OTH"]);
export type State = z.infer<typeof StateSchema>;
export const CountryCodeSchema = z.enum([
    "AF",
    "AX",
    "AL",
    "DZ",
    "AS",
    "AD",
    "AO",
    "AI",
    "AQ",
    "AG",
    "AR",
    "AM",
    "AW",
    "AU",
    "AT",
    "AZ",
    "BS",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BQ",
    "BA",
    "BW",
    "BV",
    "BR",
    "IO",
    "BN",
    "BG",
    "BF",
    "BI",
    "CV",
    "KH",
    "CM",
    "CA",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CX",
    "CC",
    "CO",
    "KM",
    "CG",
    "CD",
    "CK",
    "CR",
    "CI",
    "HR",
    "CU",
    "CW",
    "CY",
    "CZ",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "SZ",
    "ET",
    "FK",
    "FO",
    "FJ",
    "FI",
    "FR",
    "GF",
    "PF",
    "TF",
    "GA",
    "GM",
    "GE",
    "DE",
    "GH",
    "GI",
    "GR",
    "GL",
    "GD",
    "GP",
    "GU",
    "GT",
    "GG",
    "GN",
    "GW",
    "GY",
    "HT",
    "HM",
    "VA",
    "HN",
    "HK",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IM",
    "IL",
    "IT",
    "JM",
    "JP",
    "JE",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KP",
    "KR",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MT",
    "MH",
    "MQ",
    "MR",
    "MU",
    "YT",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "ME",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NC",
    "NZ",
    "NI",
    "NE",
    "NG",
    "NU",
    "NF",
    "MK",
    "MP",
    "NO",
    "OM",
    "PK",
    "PW",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PN",
    "PL",
    "PT",
    "PR",
    "QA",
    "RE",
    "RO",
    "RU",
    "RW",
    "BL",
    "SH",
    "KN",
    "LC",
    "MF",
    "PM",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SG",
    "SX",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "GS",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SJ",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "TL",
    "TG",
    "TK",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "TC",
    "TV",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UM",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "VG",
    "VI",
    "WF",
    "EH",
    "YE",
    "ZM",
    "ZW",
]);
export type CountryCode = z.infer<typeof CountryCodeSchema>;
export const AddressSchema = z.object({
    streetAddress: z.string().min(1).max(50).optional(),
    city: z.string().min(1).max(50).optional(),
    state: StateSchema.optional(),
    postcode: z.string().regex(/^\d{4}$/).optional(),
    country: CountryCodeSchema,
});
export type Address = z.infer<typeof AddressSchema>;
export const GenderSchema = z.enum(["M", "F", "U", "X"]);
export type Gender = z.infer<typeof GenderSchema>;
export const PhoneNumberSchema = z.string();
export type PhoneNumber = z.infer<typeof PhoneNumberSchema>;
export const MobilePhoneNumberSchema = z.string();
export type MobilePhoneNumber = z.infer<typeof MobilePhoneNumberSchema>;
export const PhoneNumbersSchema = z
    .object({
        homePhone: PhoneNumberSchema.regex(/^(\d{6}|\d{10}|\d{11})$/),
        workPhone: PhoneNumberSchema.regex(/^(\d{6}|\d{10}|\d{11})$/),
        mobilePhone: MobilePhoneNumberSchema.min(10)
            .max(10)
            .regex(/^\d{10}$/),
    })
    .partial();
export type PhoneNumbers = z.infer<typeof PhoneNumbersSchema>;
export const EmployerSchema = z
    .object({
        companyName: z.string().max(50).optional(),
        ABN: z.string().regex(/^\d{2}(\s\d{3}){3}$/).optional(),
        contactNumber: PhoneNumberSchema.regex(/^(\d{6}|\d{10}|\d{11})$/),
        contactName: z.string().max(50).optional(),
    })
    .partial();
export type Employer = z.infer<typeof EmployerSchema>;
export const MemberSchema = z.object({
    id: z.string(),
    salutationTitle: SalutationTitleSchema.optional(),
    firstName: z.string().min(1).max(40),
    lastName: z.string().min(1).max(25),
    dateOfBirth: DateStringSchema.regex(/^(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/),
    tfn: z.string().regex(/^\d{8,9}$/).optional(),
    email: EmailSchema,
    residentialAddress: AddressSchema.optional(),
    correspondenceAddress: AddressSchema,
    gender: GenderSchema,
    phone: PhoneNumbersSchema,
    employer: EmployerSchema.optional(),
});
export type Member = z.infer<typeof MemberSchema>;

export const CreateMemberSchema = z.object({
    salutationTitle: SalutationTitleSchema.optional(),
    firstName: z.string().min(1).max(40),
    lastName: z.string().min(1).max(25),
    dateOfBirth: DateStringSchema.regex(/^(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/),
    tfn: z.string().regex(/^\d{8,9}$/).optional(),
    residentialAddress: AddressSchema.optional(),
    correspondenceAddress: AddressSchema,
    gender: GenderSchema,
    phone: PhoneNumbersSchema,
    employer: EmployerSchema.optional(),
});
export type CreateMember = z.infer<typeof CreateMemberSchema>;